/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ru.gostkovas.task;

public final class R {
    public static final class array {
        public static final int vipList=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int btnCancel=0x7f060001;
        public static final int btnClose=0x7f060009;
        public static final int btnCreate=0x7f060007;
        public static final int btnEdit=0x7f06000a;
        public static final int btnFileR=0x7f06000d;
        public static final int btnFileW=0x7f06000c;
        public static final int btnSave=0x7f060000;
        public static final int etName=0x7f060002;
        public static final int etText=0x7f060003;
        public static final int lvNotes=0x7f060008;
        public static final int spVip=0x7f060004;
        public static final int tvDate=0x7f060006;
        public static final int tvName=0x7f060005;
        public static final int tvText=0x7f06000b;
    }
    public static final class layout {
        public static final int edit=0x7f030000;
        public static final int item=0x7f030001;
        public static final int main=0x7f030002;
        public static final int view=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
